---
name: Matt Murphy
url: http://maltmurphy.com
description: Lautering my mind. Code and Brewing.
language: en-us
posts_per_page: 7
theme: "caevyn/skelington"
bio: I live in Maitland, NSW. You will find me writing about software and brewing.
github: "http://github.com/caevyn"
twitter: "https://twitter.com/maltmurphy"
